require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SearchSetsController do

  # This should return the minimal set of attributes required to create a valid
  # SearchSet. As you add validations to SearchSet, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SearchSetsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all search_sets as @search_sets" do
      search_set = SearchSet.create! valid_attributes
      get :index, {}, valid_session
      assigns(:search_sets).should eq([search_set])
    end
  end

  describe "GET show" do
    it "assigns the requested search_set as @search_set" do
      search_set = SearchSet.create! valid_attributes
      get :show, {:id => search_set.to_param}, valid_session
      assigns(:search_set).should eq(search_set)
    end
  end

  describe "GET new" do
    it "assigns a new search_set as @search_set" do
      get :new, {}, valid_session
      assigns(:search_set).should be_a_new(SearchSet)
    end
  end

  describe "GET edit" do
    it "assigns the requested search_set as @search_set" do
      search_set = SearchSet.create! valid_attributes
      get :edit, {:id => search_set.to_param}, valid_session
      assigns(:search_set).should eq(search_set)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SearchSet" do
        expect {
          post :create, {:search_set => valid_attributes}, valid_session
        }.to change(SearchSet, :count).by(1)
      end

      it "assigns a newly created search_set as @search_set" do
        post :create, {:search_set => valid_attributes}, valid_session
        assigns(:search_set).should be_a(SearchSet)
        assigns(:search_set).should be_persisted
      end

      it "redirects to the created search_set" do
        post :create, {:search_set => valid_attributes}, valid_session
        response.should redirect_to(SearchSet.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved search_set as @search_set" do
        # Trigger the behavior that occurs when invalid params are submitted
        SearchSet.any_instance.stub(:save).and_return(false)
        post :create, {:search_set => { "title" => "invalid value" }}, valid_session
        assigns(:search_set).should be_a_new(SearchSet)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SearchSet.any_instance.stub(:save).and_return(false)
        post :create, {:search_set => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested search_set" do
        search_set = SearchSet.create! valid_attributes
        # Assuming there are no other search_sets in the database, this
        # specifies that the SearchSet created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SearchSet.any_instance.should_receive(:update_attributes).with({ "title" => "MyString" })
        put :update, {:id => search_set.to_param, :search_set => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested search_set as @search_set" do
        search_set = SearchSet.create! valid_attributes
        put :update, {:id => search_set.to_param, :search_set => valid_attributes}, valid_session
        assigns(:search_set).should eq(search_set)
      end

      it "redirects to the search_set" do
        search_set = SearchSet.create! valid_attributes
        put :update, {:id => search_set.to_param, :search_set => valid_attributes}, valid_session
        response.should redirect_to(search_set)
      end
    end

    describe "with invalid params" do
      it "assigns the search_set as @search_set" do
        search_set = SearchSet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SearchSet.any_instance.stub(:save).and_return(false)
        put :update, {:id => search_set.to_param, :search_set => { "title" => "invalid value" }}, valid_session
        assigns(:search_set).should eq(search_set)
      end

      it "re-renders the 'edit' template" do
        search_set = SearchSet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SearchSet.any_instance.stub(:save).and_return(false)
        put :update, {:id => search_set.to_param, :search_set => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested search_set" do
      search_set = SearchSet.create! valid_attributes
      expect {
        delete :destroy, {:id => search_set.to_param}, valid_session
      }.to change(SearchSet, :count).by(-1)
    end

    it "redirects to the search_sets list" do
      search_set = SearchSet.create! valid_attributes
      delete :destroy, {:id => search_set.to_param}, valid_session
      response.should redirect_to(search_sets_url)
    end
  end

end
